# SPDX-FileCopyrightText: 2023 Julian-Samuel Gebühr
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Check existence of authentik systemd service
  ansible.builtin.stat:
    path: "{{ item.path }}"
  register: authentik_service_stat

- name: Uninstall authentik systemd services and files
  when: authentik_service_stat.stat.exists | bool
  block:
    - name: Ensure authentik systemd service is stopped
      ansible.builtin.service:
        name: "{{ item.service }}"
        state: stopped
        daemon_reload: true

    - name: Ensure authentik path does not exist
      ansible.builtin.file:
        dest: "{{ item.path }}"
        state: absent
